### ISSUE TITLE
ESP8266 with MQTT

### ISSUE THREAD

**Issue by vaidyasr** [dgomes/homeGW#11]
Hi,
I would like to use it with my ESP8266 and HA. The ESP8266 is using Wifi login and password. Still do I need to connect to my Raspberry-pi via USB, to use it in HA with serial connection?. Can I use MQTT to get the data?.

For ESP8266, what will be the connection diagram?. is that same like connecting to Arduino?.

**Comment by dgomes** [comment]
Hi,

This is just a library! You need to write your own code to connect via MQTT in the ESP8266.

In the examples dir you find code that exemplifies the use of the library, it connects through a serial interface (that one works with an arduino). If you want to use the ESP8266 and MQTT you need to start fresh.

**Comment by vaidyasr** [comment]
Finally I got my components setup. I am trying https://github.com/maragelis/433MhzToMqttBridge/blob/master/MhzToMqtt/MhzToMqtt.ino where using your HomeGW with MQTT. Am using NodeMCU as a gateway. Any idea on what pin I have to connect?. D3 or D2?. Sorry I am a newbie in flashing/setting things up.

**Comment by dgomes** [comment]
I don't own/use NodeMCU, so I can't help you there. Have you asked @maragelis ?

**Comment by maragelis** [comment]
I use D5 gpio14

**Comment by vaidyasr** [comment]
> I use D5 gpio14

Thank you @maragelis 
Do I need to modify your code to use D5?.
No signals received on serial monitor. I was able to receive using Uno per project, but I want to use MQTT.

**Comment by vaidyasr** [comment]
Thank you all. working fine.
