### ISSUE TITLE
Using more than 3 Hygerometers

### ISSUE THREAD

**Issue by vaidyasr** [dgomes/homeGW#13]
I am using the homeGW which supports 3 channels only. I believe it is the restriction with the hygerometer, as it has options to use only channels 1, 2 and 3. What if I want to use more than 3?. Do I need to use another gateway to interpret the signals?.

**Comment by dgomes** [comment]
The channels are used to identify the hygrometers. You can use more then 3, the issue is that 2 will use the same channel and you will be unable to distinguish them.
