### ISSUE TITLE
ISR_PREFIX

### ISSUE THREAD

**Issue by danilkorotkov** [dgomes/homeGW#23]
HomeGW.cpp correction to
#if defined(ESP8266)
    #define ISR_PREFIX ICACHE_RAM_ATTR
#elif defined(ESP32)
    #define ISR_PREFIX IRAM_ATTR
#else
    #define ISR_PREFIX
#endif

**Comment by dgomes** [comment]
can you open a PR :) ?

**Comment by danilkorotkov** [comment]
im a lazy nube )

**Comment by danilkorotkov** [comment]
https://github.com/danilkorotkov/Digoo-Homekit
Used your lib. Many thanks)

**Comment by dgomes** [comment]
Good work :)

Still inviting you to open a Pull Request as I have no clue what needs to be corrected

**Comment by danilkorotkov** [comment]
I’m using GitHub as a file storage only, sorry)
HomeGW.cpp
Lines from 23 to 27 should be
#if defined(ESP8266)
#define ISR_PREFIX ICACHE_RAM_ATTR
#elif defined(ESP32)
#define ISR_PREFIX IRAM_ATTR
#else
#define ISR_PREFIX
#endif
