### ISSUE TITLE
added fanju sensors support

### ISSUE THREAD

**Issue by danilkorotkov** [dgomes/homeGW#26]
hi
binary.* and fanju.* files
totally 4 files 
https://github.com/danilkorotkov/homeGW

refactored code from https://github.com/pilight/pilight/pull/464/commits/af617e1b3a939d9d1b2a35ba5bc5a22941fbd910

**Comment by dgomes** [comment]
Please open a Pull Request :)

**Comment by danilkorotkov** [comment]
> Please open a Pull Request :)

as I marked before: im using Github as a file storage. Sorry but Im not the professional programmer) 
A Pull Request sounds  for me like smth from Quantum physics)

**Comment by danilkorotkov** [comment]
pls check pull request 
this is my first…
